# Generated by Django 4.2.4 on 2023-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonawsapp', '0002_uploadedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='file',
            field=models.FileField(max_length=1000, upload_to='uploads/'),
        ),
    ]
